name: Publish to Confluence

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.5'

      - name: Build Mark
        run: |
            go build

      - name: Publish to Confluence
        run: |
          for file in $(find docs/ -type f -name '*.md'); do
            echo "> Sync $file";
            ./mark -u $CONFLUENCE_USERNAME -p $CONFLUENCE_PASSWORD -b $CONFLUENCE_API -f $file || exit 1;
            echo;
          done
        env:
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          CONFLUENCE_API: ${{ secrets.CONFLUENCE_API }}
          CONFLUENCE_API_USER: ${{ secrets.CONFLUENCE_API_USER }}
